### ISSUE TITLE
Use HSTS+HPKP to enforce HTTPS

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/sseeeedd#104]
Using HSTS and HPKP to enforce HTTPS is probably a good idea :)

See [htstpreload.org](https://hstspreload.org/) or HTML5Boilerplate's [.htaccess file](https://github.com/h5bp/server-configs-apache/blob/master/dist/.htaccess).

Also @nico3333fr's post [on Alsacreations (in french)](https://www.alsacreations.com/article/lire/1723-tour-horizon-https-et-en-tetes-de-securite.html) would help.

**Comment by ffoodd** [comment]
Even if I'd really like to play with this, It's not even usable on Github Pages — so I left it there and will probably learn how to use this at work on on  [ffoodd.fr](https://www.ffoodd.fr) one day!

**Comment by nico3333fr** [comment]
HPKP is aout to be deprecated, so better avoid this one ;)
