### ISSUE TITLE
[Fly-out] — allow first level to be a link

### ISSUE THREAD

**Issue by ffoodd** [ffoodd/sseeeedd#109]
Currently these are just buttons, but when all second level items are anchors to the same page, there's no link in menu that goes to the top of targeted page.

A simple pattern using link + button would be enough, but it'll also require a bit of JavaScript to handle `aria-expanded` on the button :)

FWIW `:focus-within` should only be used as progressive enhancement to be safe.

**Comment by nhoizey** [comment]
👍
